# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0qbuqBaj2NlSeVOwqz3NsCAd_6y81Ea
"""

!pip install ultralytics streamlit opencv-python pillow
!pip install pytelegrambotapi

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

print("Model Loaded Successfully")

import cv2
import os
from ultralytics import YOLO
from datetime import datetime
import telebot

# Telegram Bot Setup
TOKEN = "8699962447:AAFKD2vEqE4M8I4-EiXMEYu8boGg9-8x6PU"
CHAT_ID = 8599447519
bot = telebot.TeleBot(TOKEN)

def send_telegram_alert(person_count, image_path=None):
    message = f"🚨 Crowd Alert Detected!\nPeople Count: {person_count}"
    bot.send_message(CHAT_ID, message)

    if image_path:
        with open(image_path, "rb") as img:
            bot.send_photo(CHAT_ID, img)

# Load YOLO model
model = YOLO("yolov8n.pt")

# Create folder for snapshots
os.makedirs("snapshots", exist_ok=True)

def detect_crowd(video_path, threshold=15):

    cap = cv2.VideoCapture(video_path)
    alert = False

    while True:

        success, frame = cap.read()
        if not success:
            break

        results = model(frame, verbose=False)
        people_count = 0

        for result in results:
            for box in result.boxes:
                cls = int(box.cls[0])

                # person class in COCO = 0
                if cls == 0:
                    people_count += 1
                    x1, y1, x2, y2 = map(int, box.xyxy[0])
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)

        cv2.putText(
            frame,
            f"People: {people_count}",
            (20,40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (255,0,0),
            2
        )

        if people_count >= threshold:

            alert = True

            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"snapshots/{timestamp}.jpg"

            cv2.imwrite(filename, frame)

            cv2.putText(
                frame,
                "CROWD ALERT!",
                (20,80),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (0,0,255),
                3
            )

            # 🔥 Send Telegram Alert
            send_telegram_alert(people_count, filename)

        yield frame, people_count, alert

    cap.release()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import tempfile
# import cv2
# 
# from crowd_detector import detect_crowd
# 
# st.set_page_config(
#     page_title="Crowd Alert",
#     layout="wide"
# )
# 
# st.title("🚦  Crowd Monitoring System")
# 
# st.write("Upload an event video to detect crowd congestion.")
# 
# uploaded_video = st.file_uploader(
#     "Choose a video",
#     type=["mp4", "avi", "mov"]
# )
# 
# threshold = st.slider(
#     "Crowd Alert Threshold",
#     min_value=5,
#     max_value=10,
#     value=15
# )
# 
# if uploaded_video is not None:
# 
#     temp_file = tempfile.NamedTemporaryFile(delete=False)
# 
#     temp_file.write(uploaded_video.read())
# 
#     st.success("Video uploaded successfully.")
# 
#     if st.button("Start Detection"):
# 
#         frame_window = st.empty()
# 
#         people_text = st.empty()
# 
#         alert_box = st.empty()
# 
#         for frame, people_count, alert in detect_crowd(
#             temp_file.name,
#             threshold
#         ):
# 
#             frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
# 
#             frame_window.image(
#                 frame,
#                 channels="RGB",
#                 use_container_width=True
#             )
# 
#             people_text.metric(
#                 "People Detected",
#                 people_count
#             )
# 
#             if alert:
# 
#                 alert_box.error(
#                     "🚨 Crowd Alert! High congestion detected."
#                 )
# 
#             else:
# 
#                 alert_box.success(
#                     "✅ Crowd level is normal."
#                 )
# 
# st.markdown("---")
#